# Generated by Django 5.1 on 2024-09-03 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('Gold', models.IntegerField()),
                ('Silver', models.IntegerField()),
                ('Copper', models.IntegerField()),
                ('Oil', models.IntegerField()),
                ('Steel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest', models.FloatField()),
                ('sandogh', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('finish_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end', to='boors.sandogh')),
                ('start_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start', to='boors.sandogh')),
            ],
        ),
    ]
